rds:
  name: database_v*
  targets:
  - src: ["DatabaseName"]
    targetPath:
    - ["infrastructure", "RDS_DB_NAME"]
eks:
  name: eks_cluster_v*
  targets:
  - src: ["name"]
    targetPath: 
    - ["infrastructure", "EKS_CLUSTER_NAME"]
  - src: ["endpoint"]
    targetName:
    - eks_endpoint
